export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_PENDING = "LOGIN_PENDING";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const GET_USER_PENDING = "GET_USER_PENDING";

export const GET_BUDGET_SUCCESS = "GET_BUDGET_SUCCESS";
export const GET_BUDGET_ERROR = "GET_BUDGET_ERROR";
export const GET_BUDGET_PENDING = "GET_BUDGET_PENDING";

export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
export const GET_BALANCE_ERROR = "GET_BALANCE_ERROR";
export const GET_BALANCE_PENDING = "GET_BALANCE_PENDING";

export const GET_TOTAL_EXPENSE_SUCCESS = "GET_TOTAL_EXPENSE_SUCCESS";
export const GET_TOTAL_EXPENSE_ERROR = "GET_TOTAL_EXPENSE_ERROR";
export const GET_TOTAL_EXPENSE_PENDING = "GET_TOTAL_EXPENSE_PENDING";